package com.kea.bilrapport.Controller;

import com.kea.bilrapport.Klasser.Medarbejder;
import com.kea.bilrapport.Repository.MedarbejderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class Medarbejdercontroller {

    @GetMapping("/hej")
    public String hej(@RequestParam(name="name", required = false, defaultValue = "world") String name, Model model) {

        return "hej";
    }

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MedarbejderRepository medarbejderRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String navn
            , @RequestParam String email,@RequestParam long id, @RequestParam String adgangskode) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Medarbejder n = new Medarbejder();
        n.setBrugernavn(navn);
        n.setEmail(email);
        return "Saved";
    }

}

